apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: network-delay
spec:
  action: network-delay
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      - key: app
        value: devops-tooling
  networkDelay:
    latency: 100ms
    loss: 10%
    correlation: 0.5