apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill
spec:
  action: kill
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      - key: app
        value: devops-tooling
  duration: 30s